version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/php:8.4-node
    steps:
      - checkout

      # Restore Composer Cache
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-

      - run:
          name: Install PHP Dependencies
          command: composer install --prefer-dist --no-progress

      # Save Composer Cache
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # Restore NPM Cache
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
            - node-v1-

      - run:
          name: Install NPM Dependencies
          command: npm install

      # Save NPM Cache
      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Build Assets
          command: npm run build

      - run:
          name: Setup Environment
          command: |
            cp .env.example .env
            php artisan key:generate

      - run:
          name: Run Tests
          command: php artisan test

workflows:
  version: 2
  test-workflow:
    jobs:
      - build-and-test